### ISSUE TITLE
How would you implement uniqueArrayOf?

### ISSUE THREAD

**Issue by leqwasd** [rumkin/typed-props#1]
This library looks great, but some more in depth examples on adding custom methods would be welcome.

    import TypedProps from "typed-props";

    class Types extends TypedProps {}

    Types.addMethod('uniqueArrayOf', function(value, needle) {
        //First, check if it actually is array
        let isArray = Types.check(value, Types.array);
        if(isArray.length) {
            return isArray;
        }
        //Then check the "Of part"
        let isArrayOf = Types.check(value, Types.arrayOf(needle._checks[0])); // apparently this is not correct
        if(isArrayOf.length) {
            return isArrayOf;
        }

        //TODO: Then check actual values

        return true;
    });

    export default Types;

At this point, I am not yet at the part where I would actually check the uniqueness.
At first, I would like to get the "Of" part correct. So I could write uniqueArrayOf(Types.number.isRequired) or uniqueArrayOf(Types.string.isRequired) and it would validate the types first.

The problem I think I am having - I cannot get the Of(...) type in the check to make a Type for ArrayOf(...)

Also - I think I found a bug - I tried making it with .addProperty, like Types.unique.arrayOf(Types.string.isRequired), but in the check method, second param `needle` is `undefined`, but `this` is `Types{_checks: Array...}`. In addMethod `this` is equal to `needle`.

edit:
With this, I can create type from the Of() parameter, but I am not sure if this would be correct.

     let ofType = new Types();
     ofType._checks = needle._checks;
     let isArrayOf = Types.check(value, Types.arrayOf(ofType));

**Comment by rumkin** [comment]
Hi. Thanks for your question. Here an example how to realize it:

```javascript
Types.addMethod('uniqueArrayOf', function(value, type) {
    //First, check if it actually is array
    const isArray = Types.check(value, Types.array);
    if (isArray.length) {
        return isArray;
    }
    
    //Then check the "Of part"
    let uniqValues = [];
    
    const isArrayOf = value.reduce((report, value, i) => {
        // Validate value type
        let typeChecks = Types.check(value, type);
        
        if (typeChecks.length) {
            // Add issues to report
            return [
                ...report,
                // Use value's report to create new one with correct array path.
                ...typeChecks.map(({path, rule, details}) => ({
                    // Add array index to path
                    path: [i, ...path],
                    rule,
                    details,
                }))
            ];
        }
        
        // Validate uniqueness
        if (uniqValues.includes(value)) {
            return [
                ...report,
                {
                    path: [i],
                    rule: 'unique',
                    details: {
                        expect: true,
                        is: false,
                    },
                },
            ];
        }
        
        uniqValues = [...uniqValues, value];
        
        return report;
    }, []);
    
    if (isArrayOf.length) {
        return isArrayOf;
    }

    return true;
});
```
When you create your own implementation of rule sometimes you will need to define your own custom validation reports and you should to resolve property paths manually. It a little bit tricky but very flexible.

**Comment by leqwasd** [comment]
Thank you for the reply, really appreciated!

Would you have an opinion about this implementation?

    Types.addMethod('uniqueArrayOf2', function (value, needle) {
        //Check the "Of part"
        let ofType = new Types();
        ofType._checks = needle._checks;
        let isArrayOf = Types.check(value, Types.arrayOf(ofType));
        if (isArrayOf.length) {
            return isArrayOf;
        }

        let uniqValues = [];
        const isUnique = value.reduce((report, value, i) => {
            // Validate uniqueness
            if (uniqValues.includes(value)) {
                return [
                    ...report,
                    {
                        path: [i],
                        rule: 'unique',
                        details: {
                            expect: true,
                            is: false,
                        },
                    },
                ];
            }
            uniqValues = [...uniqValues, value];
            return report;
        }, []);
        if (isUnique.length) {
            return isUnique;
        }

        return true;
    });

This would make funcionallity more reusable. 

Given types:
    var spec = Types.shape({
        data: Types.shape({
            test: Types.uniqueArrayOf(Types.string.isRequired)
        })
    });
    var spec2 = Types.shape({
        data: Types.shape({
            test: Types.uniqueArrayOf2(Types.string.isRequired)
        })
    });

With data 

    var data = {
        data:{
            test: ["asd", "asd"]
        }
    };

it produces exact same result as yours.
The only difference is if I give data as

    var data = {
        data:{
            test: ["asd", "asd", undefined]
        }
    };

My check terminates at type check, and doesnt do unique check which would be all right, i think. Yours does unique and type checks at the same time.

The only thing that seems hacky is this:

        let ofType = new Types();
        ofType._checks = needle._checks;
        let isArrayOf = Types.check(value, Types.arrayOf(ofType));

**Comment by rumkin** [comment]
There is no need to clone needle type, because it will not be changed by `Types.check` anyway.

Also type instances are immutable:
```javascript
const number = Types.number;
const requiredNumber = number.isRequired;

requiredNumber === number; // false
```
This allow you to export types and shapes in your files.

Now about uniqueArrayOf. I showed how to realize custom behavior to produce more informative reports. You can realize fail-fast strategy for your goal. But according to micro-tests design it's better to split uniqueArrayOf into method `arrayOf` (which already exists) and property `uniqueItems`. And call like so:

```
Types.arrayOf(Types.number).uniqueItems;
```
