### ISSUE TITLE
TypedProps.check([ ], TypedProps.object) is considered valid?

### ISSUE THREAD

**Issue by jsteckml** [rumkin/typed-props#4]
While it's technically true that arrays are objects, this assertion doesn't seem intuitive especially since there's already a `TypedProps.array` type.

What do you think?

P.S. thanks for the great library!

**Comment by rumkin** [comment]
I agree with you. But TypedProps behaviour is copying Facebook's PropTypes where this check is simple typeof result equation. Probably in versions `1.0` it will be changed and made more strict. Currently you can use `instanceOf` or add your own checker.

Thanks for suggestion.

**Comment by rumkin** [comment]
Change landed into v1.0. Now arrays and objects will be validated separately.
